"""Write the tutorial's embedded cards (frontend/src/components/tutorial/tutorialCards.ts)
from the card data, exactly as /api/cards serves it.

The tutorial embeds its cards so it renders instantly and offline; run this
after changing any card it shows (tests/test_tutorial_cards.py fails until you do):

    cd backend && uv run python scripts/build_tutorial_cards.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND))

from app.data_loader.loader import load_all_cards  # noqa: E402
from app.game_engine.cards import make_debt_card  # noqa: E402

TARGET = BACKEND.parent / "frontend" / "src" / "components" / "tutorial" / "tutorialCards.ts"

# Export name → card id. Debt isn't in the registry: /api/cards adds one as "debt".
CARDS = {
    "EXPLORE": "neutral_explore",
    "GATHER": "neutral_gather",
    "LEVY": "neutral_recruit",
    "MERCENARY": "neutral_mercenary",
    "WATCHTOWER": "neutral_watchtower",
    "BARRICADE": "neutral_fortified_post",
    "SIEGE_TOWER": "neutral_siege_tower",
    "SPOILS": "spoils",
    "RUBBLE": "rubble",
    "DEBT": "debt",
}

HEADER = """import type { Card } from '../../types/game';

/**
 * The tutorial's example cards — real card data (as /api/cards serves it),
 * embedded so the tutorial renders instantly and offline. Easy cards on
 * purpose: the two starters, simple claims, a defense, a fortification, the
 * base-raid cards and Debt.
 *
 * Generated by backend/scripts/build_tutorial_cards.py — don't edit by hand.
 */
"""


def card_data() -> dict[str, dict]:
    registry = load_all_cards()
    out: dict[str, dict] = {}
    for name, cid in CARDS.items():
        if cid == "debt":
            data = make_debt_card().to_dict()
            data["id"] = "debt"
        else:
            data = registry[cid].to_dict()
        out[name] = data
    return out


def render() -> str:
    blocks = [f"export const {name}: Card = {json.dumps(data, indent=2, ensure_ascii=False)};\n"
              for name, data in card_data().items()]
    return HEADER + "\n" + "\n".join(blocks)


if __name__ == "__main__":
    TARGET.write_text(render())
    print(f"Wrote {len(CARDS)} cards to {TARGET.relative_to(BACKEND.parent)}")
