"""initial_schema

Revision ID: bbffeaccfe47
Revises: 
Create Date: 2026-04-07 00:01:58.357136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbffeaccfe47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_clash_aggregate_stats',
    sa.Column('stat_key', sa.Text(), nullable=False),
    sa.Column('stat_value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('stat_key')
    )
    op.create_table('card_clash_games',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('state_snapshot', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('map_seed', sa.Text(), nullable=False),
    sa.Column('card_pack', sa.Text(), nullable=False),
    sa.Column('grid_size', sa.Text(), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_clash_game_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Text(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Text(), nullable=True),
    sa.Column('card_name', sa.Text(), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['card_clash_games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_clash_game_players',
    sa.Column('game_id', sa.Text(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('player_name', sa.Text(), nullable=False),
    sa.Column('archetype', sa.Text(), nullable=False),
    sa.Column('is_cpu', sa.Boolean(), nullable=False),
    sa.Column('final_vp', sa.Integer(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['card_clash_games.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_clash_game_players')
    op.drop_table('card_clash_game_events')
    op.drop_table('card_clash_games')
    op.drop_table('card_clash_aggregate_stats')
    # ### end Alembic commands ###
