import type { Card } from '../../types/game';

/**
 * The tutorial's example cards — real card data (as /api/cards serves it),
 * embedded so the tutorial renders instantly and offline. Easy cards on
 * purpose: the two starters, simple claims, a defense, a fortification and
 * the base-raid cards. Regenerate from the backend if their text changes.
 */

export const EXPLORE: Card = {
  "id": "neutral_explore",
  "definition_id": "neutral_explore",
  "name": "Explore",
  "archetype": "shared",
  "card_type": "claim",
  "power": 0,
  "resource_gain": 0,
  "action_return": 0,
  "action_cost": 1,
  "timing": "immediate",
  "buy_cost": null,
  "is_upgraded": false,
  "trash_on_use": false,
  "trash_immune": false,
  "stackable": false,
  "granted_stackable": false,
  "reversible": true,
  "forced_discard": 0,
  "draw_cards": 0,
  "defense_bonus": 0,
  "adjacency_required": true,
  "claim_range": 1,
  "unoccupied_only": true,
  "multi_target_count": 0,
  "defense_target_count": 1,
  "flood": false,
  "target_own_tile": false,
  "passive_vp": 0,
  "vp_formula": "",
  "unique": false,
  "description": "Claim: Power 0 on any adjacent unoccupied tile.",
  "upgrade_description": "Claim: Power 1. Draw 1 card.",
  "name_upgraded": "Explore+",
  "starter": true,
  "effects": [],
  "upgraded_stats": {
    "power": 1,
    "draw_cards": 1
  }
};

export const GATHER: Card = {
  "id": "neutral_gather",
  "definition_id": "neutral_gather",
  "name": "Gather",
  "archetype": "shared",
  "card_type": "engine",
  "power": 0,
  "resource_gain": 2,
  "action_return": 0,
  "action_cost": 1,
  "timing": "immediate",
  "buy_cost": null,
  "is_upgraded": false,
  "trash_on_use": false,
  "trash_immune": false,
  "stackable": false,
  "granted_stackable": false,
  "reversible": false,
  "forced_discard": 0,
  "draw_cards": 0,
  "defense_bonus": 0,
  "adjacency_required": true,
  "claim_range": 1,
  "unoccupied_only": false,
  "multi_target_count": 0,
  "defense_target_count": 1,
  "flood": false,
  "target_own_tile": false,
  "passive_vp": 0,
  "vp_formula": "",
  "unique": false,
  "description": "Gain 2 resources.",
  "upgrade_description": "Gain 3 resources. Gain 1 action.",
  "name_upgraded": "Gather+",
  "starter": true,
  "effects": [],
  "upgraded_stats": {
    "resource_gain": 3,
    "action_return": 1
  }
};

export const LEVY: Card = {
  "id": "neutral_recruit",
  "definition_id": "neutral_recruit",
  "name": "Levy",
  "archetype": "shared",
  "card_type": "claim",
  "power": 1,
  "resource_gain": 0,
  "action_return": 1,
  "action_cost": 1,
  "timing": "immediate",
  "buy_cost": 2,
  "is_upgraded": false,
  "trash_on_use": false,
  "trash_immune": false,
  "stackable": false,
  "granted_stackable": false,
  "reversible": false,
  "forced_discard": 0,
  "draw_cards": 0,
  "defense_bonus": 0,
  "adjacency_required": true,
  "claim_range": 1,
  "unoccupied_only": false,
  "multi_target_count": 0,
  "defense_target_count": 1,
  "flood": false,
  "target_own_tile": false,
  "passive_vp": 0,
  "vp_formula": "",
  "unique": false,
  "description": "Claim: Power 1. Gain 1 action.",
  "upgrade_description": "Claim: Power 2. Gain 1 action.",
  "name_upgraded": "Levy+",
  "starter": false,
  "effects": [],
  "upgraded_stats": {
    "power": 2
  }
};

export const MERCENARY: Card = {
  "id": "neutral_mercenary",
  "definition_id": "neutral_mercenary",
  "name": "Mercenary",
  "archetype": "shared",
  "card_type": "claim",
  "power": 3,
  "resource_gain": 0,
  "action_return": 0,
  "action_cost": 1,
  "timing": "immediate",
  "buy_cost": 3,
  "is_upgraded": false,
  "trash_on_use": false,
  "trash_immune": false,
  "stackable": false,
  "granted_stackable": false,
  "reversible": false,
  "forced_discard": 0,
  "draw_cards": 0,
  "defense_bonus": 0,
  "adjacency_required": true,
  "claim_range": 1,
  "unoccupied_only": false,
  "multi_target_count": 0,
  "defense_target_count": 1,
  "flood": false,
  "target_own_tile": false,
  "passive_vp": 0,
  "vp_formula": "",
  "unique": false,
  "description": "Claim: Power 3. You must pay 2 resources to play this card.",
  "upgrade_description": "Claim: Power 4. You must pay 2 resources to play this card.",
  "name_upgraded": "Mercenary+",
  "starter": false,
  "effects": [
    {
      "type": "play_resource_cost",
      "condition": "always",
      "value": 2,
      "target": "self",
      "condition_threshold": 0,
      "metadata": {}
    }
  ],
  "upgraded_stats": {
    "power": 4
  }
};

export const WATCHTOWER: Card = {
  "id": "neutral_watchtower",
  "definition_id": "neutral_watchtower",
  "name": "Watchtower",
  "archetype": "shared",
  "card_type": "defense",
  "power": 0,
  "resource_gain": 0,
  "action_return": 1,
  "action_cost": 1,
  "timing": "immediate",
  "buy_cost": 2,
  "is_upgraded": false,
  "trash_on_use": false,
  "trash_immune": false,
  "stackable": false,
  "granted_stackable": false,
  "reversible": false,
  "forced_discard": 0,
  "draw_cards": 0,
  "defense_bonus": 2,
  "adjacency_required": true,
  "claim_range": 1,
  "unoccupied_only": false,
  "multi_target_count": 0,
  "defense_target_count": 1,
  "flood": false,
  "target_own_tile": false,
  "passive_vp": 0,
  "vp_formula": "",
  "unique": false,
  "description": "One tile you own gains +2 defense this round. Gain 1 action.",
  "upgrade_description": "One tile you own gains +3 defense this round. Draw 1 card. Gain 1 action.",
  "name_upgraded": "Watchtower+",
  "starter": false,
  "effects": [],
  "upgraded_stats": {
    "draw_cards": 1,
    "defense_bonus": 3
  }
};

export const BARRICADE: Card = {
  "id": "neutral_fortified_post",
  "definition_id": "neutral_fortified_post",
  "name": "Barricade",
  "archetype": "shared",
  "card_type": "defense",
  "power": 0,
  "resource_gain": 0,
  "action_return": 0,
  "action_cost": 1,
  "timing": "immediate",
  "buy_cost": 5,
  "is_upgraded": false,
  "trash_on_use": false,
  "trash_immune": false,
  "stackable": false,
  "granted_stackable": false,
  "reversible": true,
  "forced_discard": 0,
  "draw_cards": 0,
  "defense_bonus": 0,
  "adjacency_required": true,
  "claim_range": 1,
  "unoccupied_only": false,
  "multi_target_count": 0,
  "defense_target_count": 1,
  "flood": false,
  "target_own_tile": false,
  "passive_vp": 0,
  "vp_formula": "",
  "unique": false,
  "description": "One tile you own permanently gains +2 defense until captured.",
  "upgrade_description": "One tile you own permanently gains +3 defense until captured.",
  "name_upgraded": "Barricade+",
  "starter": false,
  "effects": [
    {
      "type": "permanent_defense",
      "condition": "always",
      "value": 2,
      "target": "self",
      "condition_threshold": 0,
      "metadata": {
        "upgraded_value": 3
      }
    }
  ]
};

export const SIEGE_TOWER: Card = {
  "id": "neutral_siege_tower",
  "definition_id": "neutral_siege_tower",
  "name": "Siege Tower",
  "archetype": "shared",
  "card_type": "claim",
  "power": 6,
  "resource_gain": 0,
  "action_return": 0,
  "action_cost": 2,
  "timing": "immediate",
  "buy_cost": 9,
  "is_upgraded": false,
  "trash_on_use": false,
  "trash_immune": false,
  "stackable": false,
  "granted_stackable": false,
  "reversible": true,
  "forced_discard": 0,
  "draw_cards": 0,
  "defense_bonus": 0,
  "adjacency_required": true,
  "claim_range": 1,
  "unoccupied_only": false,
  "multi_target_count": 0,
  "defense_target_count": 1,
  "flood": false,
  "target_own_tile": false,
  "passive_vp": 0,
  "vp_formula": "",
  "unique": true,
  "description": "Claim: Power 6. Costs 2 actions to play.",
  "upgrade_description": "Claim: Power 8. Costs 2 actions to play.",
  "name_upgraded": "Siege Tower+",
  "starter": false,
  "effects": [],
  "upgraded_stats": {
    "power": 8
  }
};

export const SPOILS: Card = {
  "id": "spoils",
  "definition_id": "spoils",
  "name": "Spoils",
  "archetype": "shared",
  "card_type": "passive",
  "power": 0,
  "resource_gain": 0,
  "action_return": 0,
  "action_cost": 1,
  "timing": "immediate",
  "buy_cost": null,
  "is_upgraded": false,
  "trash_on_use": false,
  "trash_immune": false,
  "stackable": false,
  "granted_stackable": false,
  "reversible": false,
  "forced_discard": 0,
  "draw_cards": 0,
  "defense_bonus": 0,
  "adjacency_required": true,
  "claim_range": 1,
  "unoccupied_only": false,
  "multi_target_count": 0,
  "defense_target_count": 1,
  "flood": false,
  "target_own_tile": false,
  "passive_vp": 1,
  "vp_formula": "",
  "unique": false,
  "description": "Spoils of a successful base raid. Worth 1 VP.",
  "upgrade_description": "",
  "name_upgraded": "",
  "starter": false,
  "effects": []
};

export const RUBBLE: Card = {
  "id": "rubble",
  "definition_id": "rubble",
  "name": "Rubble",
  "archetype": "shared",
  "card_type": "passive",
  "power": 0,
  "resource_gain": 0,
  "action_return": 0,
  "action_cost": 1,
  "timing": "immediate",
  "buy_cost": null,
  "is_upgraded": false,
  "trash_on_use": false,
  "trash_immune": false,
  "stackable": false,
  "granted_stackable": false,
  "reversible": false,
  "forced_discard": 0,
  "draw_cards": 0,
  "defense_bonus": 0,
  "adjacency_required": true,
  "claim_range": 1,
  "unoccupied_only": false,
  "multi_target_count": 0,
  "defense_target_count": 1,
  "flood": false,
  "target_own_tile": false,
  "passive_vp": 0,
  "vp_formula": "",
  "unique": false,
  "description": "Dead weight from a base raid. Takes up a hand slot.",
  "upgrade_description": "",
  "name_upgraded": "",
  "starter": false,
  "effects": []
};
