/**
 * Card-art loading and preloading.
 *
 * Card art lives in /public/cards/<definition_id>.png (source art) with a
 * compressed sibling <definition_id>.webp generated by
 * `frontend/scripts/optimize_images.py` (~40 KB instead of ~500 KB). We load
 * the WebP first and fall back to the PNG, then to the emoji placeholder.
 *
 * Preloading has two tiers so it never competes with gameplay:
 *  - "high": cards the player is about to look at (hand, deck, markets).
 *    Fetched immediately with a small concurrency cap and decoded ahead of
 *    time so the first hover paints instantly. The most recent decoded
 *    images are retained (bounded LRU) so the browser doesn't evict them.
 *  - "idle": everything else in the catalog. Fetched one or two at a time
 *    in requestIdleCallback slots, only while the tab is visible, and
 *    skipped entirely on Save-Data / 2G connections. These only warm the
 *    HTTP cache — no decoded bitmaps are kept in memory.
 */

type Priority = 'high' | 'idle';
type Status = 'loading' | 'ready' | 'failed';

const status = new Map<string, Status>();
/** Ids whose WebP failed (missing file / old browser) — use the PNG. */
const webpFailed = new Set<string>();
/** Bounded LRU of decoded high-priority images. */
const retained = new Map<string, HTMLImageElement>();
const MAX_RETAINED = 28;

const highQueue: string[] = [];
const idleQueue: string[] = [];
const queued = new Set<string>();
let highInFlight = 0;
let idleInFlight = 0;
const HIGH_CONCURRENCY = 6;
const IDLE_CONCURRENCY = 2;
let idleScheduled = false;

const readyListeners = new Map<string, Set<() => void>>();

/** Catalog entries whose art file uses the runtime definition id. */
const ART_ALIASES: Record<string, string> = {
  rubble: 'neutral_rubble',
  spoils: 'neutral_spoils',
};

function artId(definitionId: string): string {
  return ART_ALIASES[definitionId] ?? definitionId;
}

export function cardImageUrl(definitionId: string): string {
  return webpFailed.has(definitionId)
    ? `/cards/${artId(definitionId)}.png`
    : `/cards/${artId(definitionId)}.webp`;
}

export function cardImagePngUrl(definitionId: string): string {
  return `/cards/${artId(definitionId)}.png`;
}

/** True when the image has finished loading (and decoding, for high-priority loads). */
export function isCardImageReady(definitionId: string): boolean {
  return status.get(definitionId) === 'ready';
}

/** How many card faces are showing each image right now. */
const showing = new Map<string, number>();

/** A card face started (or stopped) showing this image. */
export function cardImageShowing(definitionId: string, on: boolean): void {
  const n = (showing.get(definitionId) ?? 0) + (on ? 1 : -1);
  if (n > 0) showing.set(definitionId, n); else showing.delete(definitionId);
}

/** True when the image is decoded in memory — preloaded at high priority, or
 *  on screen in another card face — so a new <img> can decode it with its
 *  first paint at no cost (no blank frame). */
export function isCardImageDecoded(definitionId: string): boolean {
  return retained.has(definitionId) || showing.has(definitionId);
}

export function isCardImageMissing(definitionId: string): boolean {
  return status.get(definitionId) === 'failed';
}

/** Record that a rendered <img> finished loading, so later mounts skip the fade-in. */
export function markCardImageReady(definitionId: string): void {
  setStatus(definitionId, 'ready');
}

/** Record that the WebP failed for an id so subsequent renders use the PNG. */
export function markCardImageWebpFailed(definitionId: string): void {
  webpFailed.add(definitionId);
}

export function markCardImageMissing(definitionId: string): void {
  setStatus(definitionId, 'failed');
}

export function onCardImageReady(definitionId: string, cb: () => void): () => void {
  let set = readyListeners.get(definitionId);
  if (!set) {
    set = new Set();
    readyListeners.set(definitionId, set);
  }
  set.add(cb);
  return () => { set?.delete(cb); };
}

function setStatus(id: string, s: Status): void {
  status.set(id, s);
  if (s === 'ready') {
    const set = readyListeners.get(id);
    if (set) {
      readyListeners.delete(id);
      set.forEach(cb => cb());
    }
  }
}

function constrainedNetwork(): boolean {
  const conn = (navigator as Navigator & {
    connection?: { saveData?: boolean; effectiveType?: string };
  }).connection;
  if (!conn) return false;
  return !!conn.saveData || conn.effectiveType === 'slow-2g' || conn.effectiveType === '2g';
}

function retain(id: string, img: HTMLImageElement): void {
  retained.delete(id);
  retained.set(id, img);
  while (retained.size > MAX_RETAINED) {
    const oldest = retained.keys().next().value;
    if (oldest === undefined) break;
    retained.delete(oldest);
  }
}

function loadOne(id: string, priority: Priority): Promise<void> {
  return new Promise<void>((resolve) => {
    const attempt = (url: string, isWebp: boolean) => {
      const img = new Image();
      img.decoding = 'async';
      // fetchPriority is a hint; unsupported browsers ignore it.
      (img as HTMLImageElement & { fetchPriority?: string }).fetchPriority =
        priority === 'high' ? 'high' : 'low';
      img.onload = () => {
        if (priority === 'high' && typeof img.decode === 'function') {
          img.decode()
            .catch(() => undefined)
            .then(() => {
              retain(id, img);
              setStatus(id, 'ready');
              resolve();
            });
        } else {
          setStatus(id, 'ready');
          resolve();
        }
      };
      img.onerror = () => {
        if (isWebp) {
          webpFailed.add(id);
          attempt(cardImagePngUrl(id), false);
        } else {
          setStatus(id, 'failed');
          resolve();
        }
      };
      img.src = url;
    };
    attempt(cardImageUrl(id), !webpFailed.has(id));
  });
}

function pumpHigh(): void {
  while (highInFlight < HIGH_CONCURRENCY && highQueue.length > 0) {
    const id = highQueue.shift()!;
    if (status.has(id)) continue;
    status.set(id, 'loading');
    highInFlight++;
    loadOne(id, 'high').finally(() => {
      highInFlight--;
      pumpHigh();
      scheduleIdle();
    });
  }
}

function scheduleIdle(): void {
  if (idleScheduled || idleQueue.length === 0) return;
  if (highInFlight > 0) return; // resumes when the high queue drains
  idleScheduled = true;
  const run = (deadline?: { timeRemaining: () => number }) => {
    idleScheduled = false;
    if (document.visibilityState === 'hidden') {
      document.addEventListener('visibilitychange', scheduleIdle, { once: true });
      return;
    }
    while (
      idleInFlight < IDLE_CONCURRENCY &&
      idleQueue.length > 0 &&
      (!deadline || deadline.timeRemaining() > 4)
    ) {
      const id = idleQueue.shift()!;
      if (status.has(id)) continue;
      status.set(id, 'loading');
      idleInFlight++;
      loadOne(id, 'idle').finally(() => {
        idleInFlight--;
        scheduleIdle();
      });
    }
    if (idleQueue.length > 0 && idleInFlight < IDLE_CONCURRENCY) scheduleIdle();
  };
  const ric = (window as Window & {
    requestIdleCallback?: (cb: (d: { timeRemaining: () => number }) => void, o?: { timeout: number }) => number;
  }).requestIdleCallback;
  if (ric) ric(run, { timeout: 2000 });
  else window.setTimeout(() => run(), 250);
}

/**
 * Queue card art for preloading. Already-loaded or already-queued ids are
 * skipped; queuing an id at "high" promotes it out of the idle queue.
 */
export function preloadCardImages(ids: Iterable<string | undefined | null>, priority: Priority = 'idle'): void {
  if (typeof window === 'undefined' || typeof Image === 'undefined') return;
  for (const raw of ids) {
    if (!raw) continue;
    const id = raw;
    if (status.has(id)) continue;
    if (priority === 'high') {
      if (queued.has(id)) {
        const i = idleQueue.indexOf(id);
        if (i >= 0) idleQueue.splice(i, 1);
        else continue; // already in the high queue
      }
      queued.add(id);
      highQueue.push(id);
    } else {
      if (queued.has(id) || constrainedNetwork()) continue;
      queued.add(id);
      idleQueue.push(id);
    }
  }
  if (priority === 'high') pumpHigh();
  scheduleIdle();
}

/** Starter cards every player sees in their first hand. */
export const STARTER_CARD_IDS = ['neutral_explore', 'neutral_gather'];

/** Test-only: reset module state. */
export function __resetCardImagePreloadForTests(): void {
  status.clear();
  webpFailed.clear();
  retained.clear();
  highQueue.length = 0;
  idleQueue.length = 0;
  queued.clear();
  highInFlight = 0;
  idleInFlight = 0;
  idleScheduled = false;
  readyListeners.clear();
}
